In [9]:
import numpy as np

## Creando arrays

Con la librería NumPy se pueden crear diferentes tipos de arreglos de diferentes dimensiones, tal como si fueran matrices.

Para crear un array de 0 dimensiones, lo que podríamos conocer como un escalar, se realiza de la forma siguiente:

$A_{0} = 0$

In [41]:
A0 = np.array(0)
print("A =", A0)

A = 0


Este array tiene 0 filas y 0 columnas. Esto se puede conocer con el método `shape`.

In [28]:
A0.shape

()

Para crear un array de 1 dimensión, se deberá contener su valor entre corchetes. Esta matriz tendrá un renglón y una columna.

$A_1 = [1]$

In [46]:
A1 = np.array([1])
print("A =", A1)

print("\nEste arreglo tiene " + str(A1.ndim) + " dimensión.")

A = [1]

Este arreglo tiene 1 dimensión.


Pero se puede crear un arreglo de 1 dimensión, con más elementos. Al final podemos observar que las dimensiones corresponderían a las filas y las columnas no afectan la cantidad de dimensiones.

In [51]:
A1 = np.array([1, 2, 3])
print("A =", A1)

print("\nEste arreglo tiene " + str(A1.ndim) + " dimensiones.")

A = [1 2 3]

Este arreglo tiene 1 dimensiones.


Así, cada arreglo que se genere se limita a la cantidad de corchetes que se pueden tener dentro de otro par de corchetes.

$A_n = \begin{pmatrix} 
       n_{11} & n_{12} & n_{13} & \cdots & n_{1C} \\
       n_{21} & n_{22} & n_{23} & \cdots & n_{2C} \\
       n_{31} & n_{32} & n_{33} & \cdots & n_{3C} \\
       \vdots & \vdots & \vdots & \ddots & \vdots \\
       n_{R1} & n_{R2} & n_{R3} & \cdots & n_{RC} \\
\end{pmatrix}$
Por ejemplo: 
$A = \begin{pmatrix} 
       1 & 2 & 3\\
       4 & 5 & 6\\
       7 & 8 & 9\\
\end{pmatrix}$

In [76]:
A = np.array([
#eje 0  1  2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])
print(A)
print("\nEste arreglo tiene " + str(A.ndim) + " dimensiones.")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Este arreglo tiene 2 dimensiones.


También se puede obtener el tamaño de la matriz, es decir, la cantidad de elementos que contiene. Esto se realiza con el método `size`.

In [59]:
print("El arreglo anterior contiene " + str(A.size) + " elementos.")

El arreglo anterior contiene 9 elementos.


En los arreglos de NumPy se puede acceder a los elementos de igual forma que en las listas de Python. Mediante notación de índices.

In [64]:
B = np.array([0,1,2,3,4,5])
print("B =", B)

print("\nB[0] =", B[0])
print("B[:] =", B[:])
print("B[0:-1] =", B[0:-1])
print("B[::2] =", B[::2])

B = [0 1 2 3 4 5]

B[0] = 0
B[:] = [0 1 2 3 4 5]
B[0:-1] = [0 1 2 3 4]
B[::2] = [0 2 4]


Además de esto, se pueden acceder a los elementos de una matriz de más dimensiones. Esto se hace con varios índices entre corchetes que van seguidos.

*A[dimN][elementMdeN]*

O bien, usando una coma para especificar cada índice de cada dimensión.

*A[dim1, dim2, dim3, ..., dimN]*

In [70]:
print(A)
print("\nA[1][0] =", A[1][0])
print("A[1, 0] =", A[1, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

A[1][0] = 4
A[1, 0] = 4


In [75]:
print(A[:, :2])   #Se toman todos los elementos de la primer dimensión y se escogen los elementos desde el primero hasta uno antes del índice 2.

[[1 2]
 [4 5]
 [7 8]]


In [78]:
print(A[:2, :2])

[[1 2]
 [4 5]]


In [79]:
print(A[:2, 2:])

[[3]
 [6]]


También, se pueden modificar los valores que contiene un arreglo a través de su indexación.

In [81]:
A[1] = np.array([0, 0, 0])
print(A)

[[1 2 3]
 [0 0 0]
 [7 8 9]]


O bien, sólo colocando un número, el cual NumPy resolverá para colocar a todos los miembros del índice que se seleccione.

In [82]:
A[2] = 1
print(A)

[[1 2 3]
 [0 0 0]
 [1 1 1]]


## Estadística con arrays en NumPy

NumPy viene con un montón de otros métodos incluidos, como la suma de todos los elementos del array o algunos otros utilizados en estadística también.

In [85]:
B.sum() # Suma de todos los elementos.

15

In [86]:
B.mean() # La media aritmética de los elementos.

2.5

In [87]:
B.std() # La desviación estándar de los elementos.

1.707825127659933

In [88]:
B.var() # La varianza asociada a estos elementos.

2.9166666666666665

In [94]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(A)

print("\nSuma =", A.sum())
print("Media artimética =", A.mean())
print("Desviación estándar =", A.std())
print("Varianza =", A.var())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Suma = 45
Media artimética = 5.0
Desviación estándar = 2.581988897471611
Varianza = 6.666666666666667


Algo útil, es que se pueden realizar estas mismas operaciones a los *ejes* del arreglo.

In [102]:
print("suma del eje 0:", A.sum(axis=0)) # Se suman los valores de las columnas y se obtiene un arreglo con la cantidad de resultados igual a la de columnas.
print("suma del eje 1:", A.sum(axis=1))

suma del eje 0: [12 15 18]
suma del eje 1: [ 6 15 24]


In [97]:
A.mean(axis=0)

array([4., 5., 6.])

In [98]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])